From debian:buster

RUN apt update

RUN apt install -y lsb-release ca-certificates apt-transport-https software-properties-common

RUN echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/sury-php.list

RUN apt install wget -y

RUN apt install gnupg -y

RUN wget -qO - https://packages.sury.org/php/apt.gpg | apt-key add -

RUN apt update

RUN apt install apache2 -y

RUN apt install php8.0 -y

RUN apt install php8.0-mysql php8.0-cli php8.0-common php8.0-xml php8.0-fpm php8.0-curl php8.0-mbstring php8.0-zip -y

RUN apt install curl -y

RUN curl -sS https://getcomposer.org/installer | php

RUN mv composer.phar /usr/local/bin/composer

RUN chmod +x /usr/local/bin/composer

RUN composer self-update

RUN a2enmod rewrite

WORKDIR /var/www/html

EXPOSE 80

CMD ["/usr/sbin/apachectl","-DFOREGROUND"]
